### ISSUE TITLE
Unable to parse form multi-element

### ISSUE THREAD

**Issue by ryanbyyc** [kataras/iris#104] opened 2016-05-10 20:33 UTC
For this example, I'm unable to use a multiselect. I have not tried any other element such as checkbox or file. This is a huge show-stopper for me.

```html
<select multiple="multiple" name="mydata[]">
```
Or
```html
<select multiple="multiple" name="mydata">
```

Struct:
```go
type MyDataStruct struct {
	Data    []string   `formam:"mydata"`
}
```

Handler:
```go
// Serve renders the content
func (myHandler) Serve(c *iris.Context) {
	frm := MyDataStruct{}
	if c.IsPost() {
		c.ReadForm(&frm)
		fmt.Printf("%#v", &frm)
		return
	}
	c.Write("Foo, bar.")
}
```

```
Result: `Data:[]string(nil)`
```

**Comment by kataras** [comment] 2016-05-11 13:23
@ryanbyyc  I released that you want both-directional bindings, the formam library is only for one way (client(form)->server(handler)) if you want server -> client you can use the html/template package with {{ }}.  Did i see it well?

I made an example (form->handler)  for slices and it panics me with err `index out of slice` so it's [formam's](https://github.com/monoculum/formam) problem.

**Comment by dashaus** [comment] 2016-05-11 18:30
The problem is already fixed in `formam`!

**Comment by ryanbyyc** [comment] 2016-05-11 19:13
Can confirm that thanks to @dashaus fix to `formam` I am now able to pull in multiple select values.

Please apply the patch to iris @kataras!

**Comment by kataras** [comment] 2016-05-11 19:59
No need to apply a patch, if you have the latest formam it will be working on iris too :), correct me if I'm wrong

**Comment by kataras** [comment] 2016-05-11 19:59
@dashaus  nice job !

**Closed** 2016-05-11 20:00 UTC

**Comment by kataras** [comment] 2016-05-12 01:57
```go
package main

import (
	"fmt"
	"html/template"

	"github.com/kataras/iris"
)

type Visitor struct {
	Username string
	Mail     string
	Data     []string `formam:"mydata"`
}

func main() {

	iris.Get("/", func(ctx *iris.Context) {
		ctx.ExecuteTemplate(formTemplate, "")
	})

	iris.Post("/form_action", func(ctx *iris.Context) {
		visitor := &Visitor{Data: make([]string, 0)}
		err := ctx.ReadForm(visitor)
		if err != nil {
			fmt.Println("Error when reading from form: " + err.Error())
		}
		fmt.Printf("\n Visitor: %v", visitor)
	})

	fmt.Println("Server is running at :8080")
	iris.Listen(":8080")
}

var formTemplate = template.Must(template.New("").Parse(`
<!DOCTYPE html>
<head>
<meta charset="utf-8">
</head>
<body>
<form action="/form_action" method="post">
<input type="text" name="Username" />
<br/>
<input type="text" name="Mail" /><br/>
<select multiple="multiple" name="mydata">
<option value='one'>One</option>
<option value='two'>Two</option>
<option value='three'>Three</option>
<option value='four'>Four</option>
</select>
<hr/>
<input type="submit" value="Send data" />
</form>
</body>
</html>
`))

```
