### ISSUE TITLE
pongo2 依赖导致 iris 报错

### ISSUE THREAD

**Issue by JeffreyBool** [kataras/iris#1272] opened 2019-06-06 12:08 UTC
pongo2 依赖导致 iris 报错，
![image](https://user-images.githubusercontent.com/24415888/59031640-d5813f00-8896-11e9-9b6c-d8392d7f8035.png)

**Comment by kataras** [comment] 2019-06-06 19:42
Hello @JeffreyBool ,I think you are **not** using the `go modules` to manage your dependencies, instead you are using an external tool like `dep` or `glide`, the error is caused by those tools themselves, not Iris. Your problem is exactly this one: https://github.com/kataras/iris/issues/1269#issuecomment-498204532.

The problem is that the tool downloads an older version of the pongo2 package, go to your Gopkg.toml -> search for pongo2 and set its 'branch' attritube to 'master', Iris' has correctly vendor it but for some reason the'dep' tool ignores it because it tries to grab its latest "stable" branch (**see**: [1143#issuecomment-472035292](https://github.com/kataras/iris/issues/1143#issuecomment-472035292)).

Please reply if that helped you.

**Comment by kataras** [comment] 2019-06-07 18:09
@JeffreyBool Please respond if that helped you ^ or close the issue, do the same for your previous post issues as well so new users can learn from all those solutions.

**Closed** 2019-06-07 19:55 UTC
Labels: info:help-needed
