### ISSUE TITLE
[BUG]fatal error: concurrent map writes

### ISSUE THREAD

**Issue by l306287405** [kataras/iris#1673] opened 2020-11-16 10:43 UTC
**Describe the bug**
`fatal error: concurrent map writes

goroutine 58 [running]:
runtime.throw(0x137bede, 0x15)
        /usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc0000667e0 sp=0xc0000667b0 pc=0x435472
runtime.mapassign_faststr(0x125df40, 0xc0007b0750, 0x1361786, 0x4, 0x0)
        /usr/local/go/src/runtime/map_faststr.go:211 +0x3f7 fp=0xc000066848 sp=0xc0000667e0 pc=0x4151b7
net/textproto.MIMEHeader.Add(...)
        /usr/local/go/src/net/textproto/header.go:15
net/http.Header.Add(...)
        /usr/local/go/src/net/http/header.go:28
github.com/iris-contrib/middleware/cors.(*Cors).handleActualRequest(0xc00059d9a0, 0x15a3700, 0xc0004d4990)
        /www/go/pkg/mod/github.com/iris-contrib/middleware/cors@v0.0.0-20191219204441-78279b78a367/cors.go:269 +0x128 fp=0xc0000668f8 sp=0xc000066848 pc=0xa80448
github.com/iris-contrib/middleware/cors.(*Cors).Serve(0xc00059d9a0, 0x15a3700, 0xc0004d4990)
        /www/go/pkg/mod/github.com/iris-contrib/middleware/cors@v0.0.0-20191219204441-78279b78a367/cors.go:184 +0x198 fp=0xc000066938 sp=0xc0000668f8 pc=0xa7f8f8
github.com/iris-contrib/middleware/cors.(*Cors).Serve-fm(0x15a3700, 0xc0004d4990)
        /www/go/pkg/mod/github.com/iris-contrib/middleware/cors@v0.0.0-20191219204441-78279b78a367/cors.go:165 +0x3e fp=0xc000066960 sp=0xc000066938 pc=0xa818fe
github.com/kataras/iris/v12/context.DefaultNext(0x15a3700, 0xc0004d4990)
        /www/go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1343 +0x107 fp=0xc0000669b0 sp=0xc000066960 pc=0x9161d7
github.com/kataras/iris/v12/context.(*context).Next(0xc0004d4990)
        /www/go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1352 +0x3e fp=0xc0000669d0 sp=0xc0000669b0 pc=0x91623e
zhuan-qian/go-saas/common.Recover.func1(0x15a3700, 0xc0004d4990)
        /www/edu-with-love/common/zap_logger.go:110 +0x65 fp=0xc000066a10 sp=0xc0000669d0 pc=0xc86cc5
github.com/kataras/iris/v12/context.Do(0x15a3700, 0xc0004d4990, 0xc0005ae210, 0x6, 0x6)
        /www/go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1030 +0x81 fp=0xc000066a40 sp=0xc000066a10 pc=0x915841
github.com/kataras/iris/v12/context.(*context).Do(0xc0004d4990, 0xc0005ae210, 0x6, 0x6)
        /www/go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1217 +0x55 fp=0xc000066a78 sp=0xc000066a40 pc=0x915cd5
github.com/kataras/iris/v12/core/router.(*routerHandler).HandleRequest(0xc000892440, 0x15a3700, 0xc0004d4990)
        /www/go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/core/router/handler.go:250 +0x556 fp=0xc000066b60 sp=0xc000066a78 pc=0x98af46
github.com/kataras/iris/v12/core/router.(*Router).BuildRouter.func1(0x1577760, 0xc0009721c0, 0xc00094cb00)
        /www/go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/core/router/router.go:135 +0x8f fp=0xc000066bc0 sp=0xc000066b60 pc=0x9955bf
github.com/kataras/iris/v12/core/router.(*Router).ServeHTTP(0xc0002299a0, 0x1577760, 0xc0009721c0, 0xc00094cb00)
        /www/go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/core/router/router.go:227 +0x48 fp=0xc000066be8 sp=0xc000066bc0 pc=0x990c88
net/http.serverHandler.ServeHTTP(0xc000972000, 0x1577760, 0xc0009721c0, 0xc00094cb00)
        /usr/local/go/src/net/http/server.go:2807 +0xa3 fp=0xc000066c18 sp=0xc000066be8 pc=0x73a0e3
net/http.(*conn).serve(0xc0002412c0, 0x157c6a0, 0xc00054a880)
        /usr/local/go/src/net/http/server.go:1895 +0x86c fp=0xc000066fc8 sp=0xc000066c18 pc=0x735b5c
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000066fd0 sp=0xc000066fc8 pc=0x465261
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2933 +0x35c

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7ff332e91f90, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc0008a7c18, 0x72, 0x0, 0x0, 0x1366640)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0008a7c00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:384 +0x1d4
net.(*netFD).accept(0xc0008a7c00, 0xe3a83bba61a7a2e0, 0x0, 0xe3a83bba61a7a2e0)
        /usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc00076a000, 0x5fb25424, 0xc000905be8, 0x48e3c6)
        /usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc00076a000, 0xc000905c38, 0x18, 0xc000000180, 0x73a58c)
        /usr/local/go/src/net/tcpsock.go:261 +0x64
net/http.(*Server).Serve(0xc000972000, 0x15774a0, 0xc00076a000, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2901 +0x25d
github.com/kataras/iris/v12/core/host.(*Supervisor).Serve.func1(0xc000974000, 0xc000974000)
        /www/go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/core/host/supervisor.go:217 +0x3f
github.com/kataras/iris/v12/core/host.(*Supervisor).supervise(0xc000974000, 0xc000905dd8, 0xc00076a000, 0x0)
        /www/go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/core/host/supervisor.go:193 +0x3e
github.com/kataras/iris/v12/core/host.(*Supervisor).Serve(0xc000974000, 0x15774a0, 0xc00076a000, 0x0, 0x0)
        /www/go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/core/host/supervisor.go:217 +0x67
github.com/kataras/iris/v12/core/host.(*Supervisor).ListenAndServe(0xc000974000, 0x0, 0x0)
        /www/go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/core/host/supervisor.go:229 +0x5c
github.com/kataras/iris/v12.Addr.func1(0xc000116630, 0xc000000005, 0x1390337)
        /www/go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/iris.go:844 +0xb6
github.com/kataras/iris/v12.(*Application).Run(0xc000116630, 0xc0004c3650, 0xc000905f70, 0x1, 0x1, 0xc0004c3650, 0x6)
        /www/go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/iris.go:982 +0x1d1
main.main()
        /www/edu-with-love/main.go:21 +0xf5

goroutine 22 [select]:
database/sql.(*DB).connectionOpener(0xc000102300, 0x157c6a0, 0xc0001a9040)
        /usr/local/go/src/database/sql/sql.go:1052 +0xe8
created by database/sql.OpenDB
        /usr/local/go/src/database/sql/sql.go:722 +0x15d

goroutine 23 [select]:
database/sql.(*DB).connectionResetter(0xc000102300, 0x157c6a0, 0xc0001a9040)
        /usr/local/go/src/database/sql/sql.go:1065 +0xfb
created by database/sql.OpenDB
        /usr/local/go/src/database/sql/sql.go:723 +0x193

goroutine 8 [select]:
github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1(0xc00028c000, 0xc000498000, 0xc00008a0c0)
        /www/go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/connection.go:621 +0xbf
created by github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher
        /www/go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/connection.go:618 +0xbe

goroutine 52 [select]:
database/sql.(*DB).connectionOpener(0xc000102480, 0x157c6a0, 0xc00054a2c0)
        /usr/local/go/src/database/sql/sql.go:1052 +0xe8
created by database/sql.OpenDB
        /usr/local/go/src/database/sql/sql.go:722 +0x15d

goroutine 38 [runnable]:
net/http.(*connReader).backgroundRead(0xc0007b0600)
        /usr/local/go/src/net/http/server.go:677
created by net/http.(*connReader).startBackgroundRead
        /usr/local/go/src/net/http/server.go:674 +0xd0

goroutine 55 [select]:
database/sql.(*DB).connectionResetter(0xc000102600, 0x157c6a0, 0xc00054a440)
        /usr/local/go/src/database/sql/sql.go:1065 +0xfb
created by database/sql.OpenDB
        /usr/local/go/src/database/sql/sql.go:723 +0x193

goroutine 53 [select]:
database/sql.(*DB).connectionResetter(0xc000102480, 0x157c6a0, 0xc00054a2c0)
        /usr/local/go/src/database/sql/sql.go:1065 +0xfb
created by database/sql.OpenDB
        /usr/local/go/src/database/sql/sql.go:723 +0x193

goroutine 54 [select]:
database/sql.(*DB).connectionOpener(0xc000102600, 0x157c6a0, 0xc00054a440)
        /usr/local/go/src/database/sql/sql.go:1052 +0xe8
created by database/sql.OpenDB
        /usr/local/go/src/database/sql/sql.go:722 +0x15d

goroutine 28 [select]:
github.com/olivere/elastic/v7.(*Client).healthchecker(0xc0000ad520)
        /www/go/pkg/mod/github.com/olivere/elastic/v7@v7.0.19/client.go:1060 +0x169
created by github.com/olivere/elastic/v7.DialContext
        /www/go/pkg/mod/github.com/olivere/elastic/v7@v7.0.19/client.go:406 +0x600

goroutine 16 [IO wait]:
internal/poll.runtime_pollWait(0x7ff332e91cf0, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc00071ba18, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00071ba00, 0xc00036b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc00071ba00, 0xc00036b000, 0x1000, 0x1000, 0xc00007c600, 0xc000067da8, 0xc000067c38)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0000117e0, 0xc00036b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:184 +0x8e
net/http.(*persistConn).Read(0xc00048e6c0, 0xc00036b000, 0x1000, 0x1000, 0xc000067eb0, 0x462500, 0xc000067eb0)
        /usr/local/go/src/net/http/transport.go:1825 +0x75
bufio.(*Reader).fill(0xc0000aad20)
        /usr/local/go/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).Peek(0xc0000aad20, 0x1, 0x2, 0x0, 0x0, 0xc000038800, 0x0)
        /usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc00048e6c0)
        /usr/local/go/src/net/http/transport.go:1978 +0x1a8
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1647 +0xc56

goroutine 34 [select]:
net/http.(*persistConn).writeLoop(0xc00048e6c0)
        /usr/local/go/src/net/http/transport.go:2277 +0x11c
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1648 +0xc7b

goroutine 36 [select]:
github.com/robfig/cron/v3.(*Cron).run(0xc00059d900)
        /www/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:263 +0x541
created by github.com/robfig/cron/v3.(*Cron).Start
        /www/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:222 +0xa4

goroutine 37 [chan receive]:
github.com/kataras/iris/v12/core/host.(*interruptListener).notifyAndFire(0xc0003f8bd0)
        /www/go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/core/host/interrupt.go:72 +0xd3
created by github.com/kataras/iris/v12/core/host.(*interruptListener).listenOnce.func1
        /www/go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/core/host/interrupt.go:57 +0x3e

goroutine 29 [syscall]:
os/signal.signal_recv(0xc0000aade0)
        /usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.Notify.func1
        /usr/local/go/src/os/signal/signal.go:127 +0x44

goroutine 56 [select]:
github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1(0xc0000abec0, 0xc0004990e0, 0xc000910d80)
        /www/go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/connection.go:621 +0xbf
created by github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher
        /www/go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/connection.go:618 +0xbe

goroutine 57 [runnable]:
github.com/iris-contrib/middleware/jwt.logf(0x15a3700, 0xc0004d4000, 0x1378c22, 0x13, 0xc0008fd570, 0x1, 0x1)
        /www/go/pkg/mod/github.com/iris-contrib/middleware/jwt@v0.0.0-20191219204441-78279b78a367/jwt.go:107 +0xa0
github.com/iris-contrib/middleware/jwt.(*Middleware).CheckJWT(0xc0002283c0, 0x15a3700, 0xc0004d4000, 0x11179c0, 0x4145fe)
        /www/go/pkg/mod/github.com/iris-contrib/middleware/jwt@v0.0.0-20191219204441-78279b78a367/jwt.go:201 +0x1d0
github.com/iris-contrib/middleware/jwt.(*Middleware).Serve(0xc0002283c0, 0x15a3700, 0xc0004d4000)
        /www/go/pkg/mod/github.com/iris-contrib/middleware/jwt@v0.0.0-20191219204441-78279b78a367/jwt.go:118 +0x43
github.com/kataras/iris/v12/context.DefaultNext(0x15a3700, 0xc0004d4000)
        /www/go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1343 +0x107
github.com/kataras/iris/v12/context.(*context).Next(0xc0004d4000)
        /www/go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1352 +0x3e
zhuan-qian/go-saas/app/middleware.LoggerHandler(0x15a3700, 0xc0004d4000)
        /www/edu-with-love/app/middleware/logger.go:45 +0x65d
github.com/kataras/iris/v12/context.DefaultNext(0x15a3700, 0xc0004d4000)
        /www/go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1343 +0x107
github.com/kataras/iris/v12/context.(*context).Next(0xc0004d4000)
        /www/go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1352 +0x3e
github.com/iris-contrib/middleware/cors.(*Cors).Serve(0xc00059d9a0, 0x15a3700, 0xc0004d4000)
        /www/go/pkg/mod/github.com/iris-contrib/middleware/cors@v0.0.0-20191219204441-78279b78a367/cors.go:185 +0x1af
github.com/kataras/iris/v12/context.DefaultNext(0x15a3700, 0xc0004d4000)
        /www/go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1343 +0x107
github.com/kataras/iris/v12/context.(*context).Next(0xc0004d4000)
        /www/go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1352 +0x3e
zhuan-qian/go-saas/common.Recover.func1(0x15a3700, 0xc0004d4000)
        /www/edu-with-love/common/zap_logger.go:110 +0x65
github.com/kataras/iris/v12/context.Do(0x15a3700, 0xc0004d4000, 0xc0005ae210, 0x6, 0x6)
        /www/go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1030 +0x81
github.com/kataras/iris/v12/context.(*context).Do(0xc0004d4000, 0xc0005ae210, 0x6, 0x6)
        /www/go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1217 +0x55
github.com/kataras/iris/v12/core/router.(*routerHandler).HandleRequest(0xc000892440, 0x15a3700, 0xc0004d4000)
        /www/go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/core/router/handler.go:250 +0x556
github.com/kataras/iris/v12/core/router.(*Router).BuildRouter.func1(0x1577760, 0xc0008f01c0, 0xc0004b8500)
        /www/go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/core/router/router.go:135 +0x8f
github.com/kataras/iris/v12/core/router.(*Router).ServeHTTP(0xc0002299a0, 0x1577760, 0xc0008f01c0, 0xc0004b8500)
        /www/go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/core/router/router.go:227 +0x48
net/http.serverHandler.ServeHTTP(0xc000972000, 0x1577760, 0xc0008f01c0, 0xc0004b8500)
        /usr/local/go/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc000241180, 0x157c6a0, 0xc0001c8240)
        /usr/local/go/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2933 +0x35c

goroutine 59 [runnable]:
net/http.(*connReader).backgroundRead(0xc0004cd6e0)
        /usr/local/go/src/net/http/server.go:677
created by net/http.(*connReader).startBackgroundRead
        /usr/local/go/src/net/http/server.go:674 +0xd0
exit status 2`

**To Reproduce**
1. ab -n 500 -c 100 -H "Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50IjoiMTMwMTIzNDEyMzQiLCJleHAiOjE2MDYxMjExOTYsImlkIjoxLCJuaWNrbmFtZSI6ImFkbWluIiwic3RhdHVzIjoxfQ.KHyoKeDzFqW1ShrLQLRvJar29zpeHuzcRlh6XgGKEpA" love.yeshine61.com/admins/info
2. There is a certain probability of occurrence.

**Desktop (please complete the following information):**
ubuntu

**iris.Version**
v12.1.8

**Comment by kataras** [comment] 2020-11-16 11:37
Hello @l306287405, 

Generally speaking, you should always upgrade to our master version(`@master`) before opening a new issue. 
I want to help you but I don't see any **code snippet**? I don't see any Iris-relative concurrentcy errors in the logs above, Iris is checked by tools to make sure we don't have that type of problems, maybe it's something in your own code? Or you use a feature that is not supposed to run inside a request handler?


Waiting for your response,
Gerasimos Maropoulos

**Comment by l306287405** [comment] 2020-11-17 02:29
This problem occurs in one of my middleware,
It is used to verify that jwt is valid or removed.

User login an account and get a jwt,then use ab to test to get admins.Info,
This code of router:
```
func AdminRouter(app *iris.Application) {
	app.Options("/{any:path}", func(ctx iris.Context) {})

	mvc.Configure(app.Party("/admins"), func(m *mvc.Application) {
		var (
			unauth   = m.Party("/", middleware.LoggerHandler).Register(validator.New())
			authUser = m.Party("/", middleware.LoggerHandler, middleware.AdminJS, middleware.AdminsVerify).Register(validator.New())
		)

		unauth.Party("/token").Handle(new(admins.AdminsToken))
		authUser.Party("/info").Handle(new(admins.Info))
	})
}
```

admins_verify.go:
```

import (
	"errors"
	"fmt"
	"github.com/iris-contrib/middleware/jwt"
	"github.com/kataras/iris/v12"
	"net/http"
	"os"
	"strings"
	"zhuan-qian/go-saas/common"
	"zhuan-qian/go-saas/model"
	"zhuan-qian/go-saas/service"
)

var AdminJS = jwt.New(jwt.Config{
	// 通过 "token" URL参数提取。
	Extractor: func(ctx iris.Context) (string, error) {
		token := ctx.GetHeader('Authorization')
		if token == "" {
			return "", errors.New("Authorization must in request header")
		}

		if !strings.HasPrefix(token, "Bearer ") {
			return "", errors.New( "Authorization header format must like as 'Bearer {token}'")
		}

		token = token[7:]
		return token, nil
	},
	//Extractor: jwt.FromAuthHeader,

	ValidationKeyGetter: func(token *jwt.Token) (interface{}, error) {
		return []byte(os.Getenv("ADMIN_TOKEN_SECRET")), nil
	},
	SigningMethod: jwt.SigningMethodHS256,
}).Serve

//管理员token校验中间件
func AdminsVerify(c iris.Context) {
	var (
		cachedToken string
		admin       *model.Admins
		info        jwt.MapClaims
		err         error

		jwtToken *jwt.Token
	)

	jwtToken = c.Values().Get("jwt").(*jwt.Token)
	if !jwtToken.Valid {
		err = errors.New("Authorization header must be a valid JWT")
		goto REQUEST_ERR
	}

	info = jwtToken.Claims.(jwt.MapClaims)

	cachedToken, err = service.NewAdminsService().GetTokenByUid(int(info["id"].(float64)))
	if err != nil {
		goto SERVER_ERR
	}

	if jwtToken.Raw != cachedToken {
		err = errors.New( "Authorization is expired or invalid")
		goto REQUEST_ERR
	}

	admin = service.NewAdminsService().ParseTokenToUser(info)

	c.Values().Set("adminInfo", admin)
	c.Next()
	return

REQUEST_ERR:
	c.StatusCode(http.StatusUnauthorized)
	c.Header("WWW-Authenticate", fmt.Sprintf(`JWT realm="%s", charset="UTF-8"`, err.Error()))
	c.StopExecution()
	c.EndRequest()
	return

SERVER_ERR:
	c.StatusCode(http.StatusInternalServerError)
	c.Header("WWW-Authenticate", fmt.Sprintf(`JWT realm="%s", charset="UTF-8"`, err.Error()))
	c.StopExecution()
	c.EndRequest()
	return
}

//NewAdminsService().ParseTokenToUser
func (s *Admins) ParseTokenToUser(jwt jwt.MapClaims) *model.Admins {
	m := &model.Admins{}
	m.Id = int(jwt["id"].(float64))
	m.Account = jwt["account"].(string)
	m.Nickname = jwt["nickname"].(string)
	m.Status = int8(jwt["status"].(float64))
	return m
}

```

admins_token.go
```
package admins

import (
	"zhuan-qian/go-saas/app/controllers"
	"zhuan-qian/go-saas/common"
	"zhuan-qian/go-saas/model"
	"zhuan-qian/go-saas/service"
)

//登录
func (c *AdminsToken) Post() {
	var (
		a     = &model.Admins{}
		token *string
		err   error
	)

	err = c.Ctx.ReadForm(a)
	if a.Account == "" || a.Password == "" {
		c.SendBadRequest("参数缺失")
		return
	}

	token, err = service.NewAdminsService().Login(a.Account, []byte(a.Password))
	if err != nil {
		if common.IsRequireError(err) {
			c.SendBadRequest(err.Error())
		} else {
			c.SendServerError(err.Error())
		}
		return
	}
	c.SendSmile(token)
	return
}
```

AdminsService
```
package service

import (
	"errors"
	"github.com/iris-contrib/middleware/jwt"
	"golang.org/x/crypto/bcrypt"
	"os"
	"strconv"
	"strings"
	"time"
	"zhuan-qian/go-saas/app/controllers/params"
	"zhuan-qian/go-saas/common"
	"zhuan-qian/go-saas/dao"
	"zhuan-qian/go-saas/model"
	"zhuan-qian/go-saas/service/cache"
)

type Admins struct {
	d *dao.Admins
}

func NewAdminsService() *Admins {
	return &Admins{d: dao.NewAdminsDao().WithSession(nil)}
}

//登录模块
func (s *Admins) Login(account string, requestPassword []byte) (token *string, err error) {
	var (
		m *model.Admins
	)

	m, err = s.d.GetByAccount(account)
	if err != nil {
		return token, err
	}
	if m == nil {
		return token, common.NewRequireError("账号或密码错误")
	}
	passwordRecord := []byte(m.Password)
	err = bcrypt.CompareHashAndPassword(passwordRecord, requestPassword)
	if err != nil {
		return token, common.NewRequireError("账号或密码错误")
	}

	token, err = s.CreateToken(m)
	if err != nil {
		return token, err
	}

	_, err = s.SetCacheOfToken(m.Id, *token)
	if err != nil {
		return token, errors.New("用户token存储失败 请联系管理员 " + err.Error())
	}

	return token, nil
}

//创建token
func (s *Admins) CreateToken(m *model.Admins) (*string, error) {
	token := jwt.NewTokenWithClaims(jwt.SigningMethodHS256, jwt.MapClaims{
		"id":       m.Id,
		"account":  m.Account,
		"nickname": m.Nickname,
		"status":   m.Status,
		"exp":      time.Now().Add(7 * 24 * time.Hour).Unix(),
	})
	tokenString, err := token.SignedString([]byte(os.Getenv("ADMIN_TOKEN_SECRET")))
	return &tokenString, err
}

//解析token存入控制器变量容器中(ctx.values())
func (s *Admins) ParseTokenToUser(jwt jwt.MapClaims) *model.Admins {
	m := &model.Admins{}
	m.Id = int(jwt["id"].(float64))
	m.Account = jwt["account"].(string)
	m.Nickname = jwt["nickname"].(string)
	m.Status = int8(jwt["status"].(float64))
	return m
}

//创建一个账号
func (s *Admins) Create(account string, password string, nickname string) (id int, err error) {
	m := &model.Admins{}
	m.Account, m.Password, m.Nickname, m.Status = account, s.d.EncryptPassword(password), nickname, 1
	_, err = s.d.Create(m)
	return m.Id, err
}

//设置token与管理员id的映射缓存
func (s *Admins) SetCacheOfToken(userId int, token string) (num int64, err error) {
	return dao.NewAdminsDao().WithSession(nil).UpdateTokenById(userId, token)
}

//获取token相关的管理员id
func (s *Admins) GetTokenByUid(userId int) (token string, err error) {
	var (
		m     = &model.Admins{}
		found bool
	)
	found, err = dao.NewAdminsDao().WithSession(nil).InfoBy([]string{"token"}, int64(userId), m)
	if err != nil {
		return
	}
	if !found {
		return token, common.NewRequireError("用户信息错误")
	}
	return m.Token, nil
}
```

info.go
```
package admins

import (
	"zhuan-qian/go-saas/app/controllers"
	"zhuan-qian/go-saas/app/controllers/params"
	"zhuan-qian/go-saas/common"
	"zhuan-qian/go-saas/dao"
	"zhuan-qian/go-saas/model"
	"zhuan-qian/go-saas/service"
	"strings"
)

type Info struct {
	controllers.Base
}

//获取员工菜单与权限
func (c *Info) Get() {
	var (
		admin     = c.Ctx.Values().Get(common.KEY_FOR_ADMIN_INFO).(*model.Admins)
		rbacDao   = dao.NewRbacDao()
		rolesName = rbacDao.GetRolesNameBy(model.ORGANIZEID_OF_BACKEND, admin.Id)
		p         = &params.MenusGet{
			IsTree:      1,
			RolesName:   common.StringPtr(strings.Join(rolesName, ",")),
			OnlyRelated: common.Int8Ptr(1),
		}
		list, err = service.NewMenusService().List(model.ORGANIZEID_OF_BACKEND, p, model.MENU_GENRE_IS_BACKEND)
		result    = make(map[string]interface{})
	)
	if err != nil {
		c.SendBadRequest(err.Error())
		return
	}
	result["menus"] = list
	result["info"] = admin
	result["roles"] = rolesName
	c.SendSmile(result)
}

```

**Comment by l306287405** [comment] 2020-11-17 02:42
If the token is valid, this error will not occur.
this token  is invalid,this error will occur.

**Comment by kataras** [comment] 2020-11-17 04:46
@l306287405 Hello, why you don't break it down to little parts to check where exactly your issue is? For example you use some third-party libraries that I am not responsible of...please break it down to little parts, I think you will find where the issue is alone if you follow my steps. If you don't, create a github repository with a docker image or a code that I can copy-paste-run and reproduce the issue.

**Comment by kataras** [comment] 2020-11-21 22:13
Closing this as you opened a new issue without responding to this one, so I assume you fixed the problem as this is not really an Iris bug.

**Closed** 2020-11-21 22:14 UTC
Labels: pending-submitter-response
