### ISSUE TITLE
I can't use iris on my goland

### ISSUE THREAD

**Issue by sssguoer** [kataras/iris#2053] opened 2023-02-06 17:42 UTC
Describe the issue you are facing or ask for help
![W%QHH)`HT88RBGUWOO(PKUD](https://user-images.githubusercontent.com/101733867/217045386-fa03bd07-5234-4adb-9502-d2d1bbe53a18.png)

![UBM9V`%$CT9~CDT~KJ9}REF](https://user-images.githubusercontent.com/101733867/217045414-45364cf9-2b7c-46c9-955b-1fed494b2aa2.png)

![2H46_G2$M6X}BPSLQFEWXO](https://user-images.githubusercontent.com/101733867/217045436-18bb98e0-1dce-4bad-92b0-af7a11236d48.png)

**Comment by kataras** [comment] 2023-02-06 22:42
You are importing `"github.com/kataras/iris"`, but you should use `"github.com/kataras/iris/v12"` with `go get github.com/kataras/iris/v12@master`.

**Comment by sssguoer** [comment] 2023-02-07 02:47
> 您正在导入 ，但应与 一起使用。`"github.com/kataras/iris"``"github.com/kataras/iris/v12"``go get github.com/kataras/iris/v12@master`
Thank you very much for your help

**Comment by kataras** [comment] 2023-02-07 14:01
You are welcome @sssguoer, have fun and if you ever need help don't hesitate to ask again!

**Comment by sayem314** [comment] 2023-05-29 20:19
Just a heads up, it seems like the issue is resolved. Can we go ahead and close it? Thanks!

**Comment by kataras** [comment] 2023-06-05 20:35
Hello @sayem314, of course. closing it.

**Closed by kataras** 2023-06-05 20:35 UTC
