### ISSUE TITLE
Build Error : kataras/iris/http.go:716: cannot use cachedHandler (type *fhttp.Handler) as type fasthttp.RequestHandler in field value

### ISSUE THREAD

**Issue by jadeblaquiere** [kataras/iris#541] opened 2016-11-18 17:01 UTC
- Version : **5.0.1**

- Operating System: Ubuntu 14.04 / golang 1.6 

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------

```
root@localhost:/usr/local/src/gobase/src/github.com# rm -rf kataras/
root@ocalhost:/usr/local/src/gobase/src/github.com# go get -u github.com/kataras/iris/iris
# github.com/kataras/iris
kataras/iris/http.go:716: cannot use cachedHandler (type *fhttp.Handler) as type fasthttp.RequestHandler in field value
```
 
the new CacheFasthttp returns type fhttp.Handler, but that looks to me to be an internal type (so really the fix would be to expose that type in httpcache, perhaps?) ...

**Comment by everyonce** [comment] 2016-11-19 00:41
This is troubling me as well, looks like it was caused by 
https://github.com/GeekyPanda/httpcache/commit/2dded99a8d7fe28f8accb80c6334f10ba1044ca8

**Comment by kataras** [comment] 2016-11-19 08:16
@jadeblaquiere  @everyonce You have right, I don't know why I forgot to update it there too, the bad is that I can't provide a stable release until it goes to v1 (because iris v4 is depends on the 0.0.1 of httpcache instead of the 0.0.3 which this iris version 5 is depends and gopkg can't target to minversions). 

Thanks for the report, it's fixed now!

**Closed** 2016-11-19 08:16 UTC
