### ISSUE TITLE
[FEATURE REQUEST] Make i18n expandable 

### ISSUE THREAD

**Issue by Dexus** [kataras/iris#1597] opened 2020-08-18 07:24 UTC
I come from the corner of GNU Gettext users. I would like to have something similar for the i18n implementation.

What requirements would I have:
- Loader (local and binary)
- Gettext functions, so that several domains and contexts can be used.
- message interfaces
- PO/MO support, JSON (i18n-next etc.), the current ini format

https://github.com/leonelquinteros/gotext (with serveral fixes: https://git.deineagentur.com/DeineAgenturUG/gotext) could serve as a basis for inspiration.

What do you think?

**Comment by kataras** [comment] 2020-08-18 08:46
Hello @Dexus , they are implemented already, u can load translations from binary, language codes are simplified automatically e.g. en to en-us, you can use variables and text templates. Can u please provide me something u want to do and u cant with the current imolementation? So I can understand the idea of urs

**Comment by Dexus** [comment] 2020-09-07 13:31
Hi @kataras 
Sorry for the delay. 

I miss the possibility to translate strings with number counts like you can do with gettext. like `ngettext("string {$1} dog", "string {$1} dogs", 24)` which will print `string 24 dogs` based on the plural variant of the language. Thats why a gettext implementation is the best and a standard in software development.

I use Gettext in all my projects a cross multiple languages, like Swift, Kotlin, Java, Javascript, PHP, C/C++ and Go. So It would reallly helpfull to load also the po/mo files from gettext within the iris project directly and not with a extra middleware that is already there with iris i18n support.

Also it would be cool, to have a function or a way to translate path for multilinguale projects, currently I run a loop over each path registration and add the language + seperator + pathName and add a own url function, that find the path for the current language and the pathName. It clould all be easy also for the alternative html tags for the different languages. But with the currently implementation it worth nothing to create multilinguale projects with the included i18n system.

Hope I was able to make my Idea a bit more clear.

Thanks, Dexus

**Comment by AlbinoGeek** [comment] 2020-09-08 00:40
Well, right now it appears that I18N is basically a `fmt.Sprintf` statement, in that it currently uses all the same formatting directives. This gives you a lot more expandability and configurability when compared to positional arguments, but it does not allow you to easily re-use the existing arguments without passing them multiple times.

I would see benefit for both frankly.

**Comment by kataras** [comment] 2020-09-09 14:02
Guys, you can use `text/template` with i18n, with that you can add functions for plural and so many things, it's not just an `fmt.Sprintf` thing...

**Comment by kataras** [comment] 2020-09-10 01:43
**main.go**

```go
package main

import (
	"github.com/kataras/iris/v12"

	// go get -u github.com/gertd/go-pluralize
	"github.com/gertd/go-pluralize"
)

func main() {
	app := newApp()
	app.Listen(":8080")
}

func newApp() *iris.Application {
	app := iris.New()

	pluralize := pluralize.NewClient()
	app.I18n.Loader.FuncMap = map[string]interface{}{
		"plural": func(word string, count int) string {
			// Your own implementation or use a 3rd-party package
			// like we do here.
			//
			// Note that this is only for english,
			// but you can accept the language code
			// and use a map with dictionaries to
			// pluralize words based on the given language.
			return pluralize.Pluralize(word, count, true)
		},
	}
	app.I18n.Load("./locales/*/*.yml", "en-US", "el-GR")

	app.Get("/", func(ctx iris.Context) {
		text := ctx.Tr("HiDogs", iris.Map{
			"locale": ctx.GetLocale(),
			"count":  2,
		}) // prints "Hi 2 dogs".
		ctx.WriteString(text)
	})

	return app
}
```

**./locales/el-GR/welcome.yml**

```yml
Dog: "σκυλί"
HiDogs: Γειά {{plural (tr .locale "Dog") .count }}
```

**./locales/en-US/welcome.yml**

```yml
Dog: "dog"
HiDogs: Hi {{plural (tr .locale "Dog") .count }}
```

**Comment by kataras** [comment] 2020-09-10 03:24
@AlbinoGeek @Dexus does something like that fills your needs or? (all those can be done before too but I pushed 3 commits to make ur life easier, so grab the master to run it)

**/main.go**

```go
package main

import (
	"text/template"

	"github.com/kataras/iris/v12"
	// go get -u github.com/gertd/go-pluralize
	"github.com/gertd/go-pluralize"
)

/*
 Iris I18n supports text/template inside the translation values.
 Follow this example to learn how to use that feature.
*/

func main() {
	app := newApp()
	app.Listen(":8080")
}

func newApp() *iris.Application {
	app := iris.New()

	pluralize := pluralize.NewClient()

	// Set custom functions per locale!
	app.I18n.Loader.Funcs = func(current iris.Locale) template.FuncMap {
		return template.FuncMap{
			"plural": func(word string, count int) string {
				// Your own implementation or use a 3rd-party package
				// like we do here.
				//
				// Note that this is only for english,
				// but you can accept the language code
				// and use a map with dictionaries to
				// pluralize words based on the given language.
				return pluralize.Pluralize(word, count, true)
			},
		}
	}

	app.I18n.Load("./locales/*/*.yml", "en-US", "el-GR")

	app.Get("/", func(ctx iris.Context) {
		text := ctx.Tr("HiDogs", iris.Map{
			"count": 2,
		}) // prints "Hi 2 dogs".
		ctx.WriteString(text)
	})

	return app
}

```


**./locales/en-US/welcome.yml**

```yml
Dog: "dog"
HiDogs: Hi {{plural (tr "Dog") .count }}
```

**./locales/el-GR/welcome.yml**

```yml
Dog: "σκυλί"
HiDogs: Γειά {{plural (tr "Dog") .count }}
```

**Comment by AlbinoGeek** [comment] 2020-09-10 05:25
I did not know that it was composable, this will save me so much re-typing if I can literally do `{{tr "otherKey"}}` in the middle of my translation strings.

**Comment by kataras** [comment] 2020-09-10 07:32
Yes with the latest commits you can do it!! Order of keys should not matter too.. And do more and more because I exposed the ability to have template functions per locale. Waiting for @Dexus confirmation too so we can move forward.

**Comment by AlbinoGeek** [comment] 2020-09-10 07:34
Would the following be valid syntax under the new commits?

```ini
; 400 error
badRequestTitle=Bad Request
badRequestDescription=There was something about your browser or entries that we could not accept, and we cannot provide any additional details. {{tr "pleaseGoBack"}}

; 500 error
internalServerErrorTitle=Internal Server Error
internalServerErrorDescription=An issue happened on our side, and we cannot provide any additional details. We apologize for the inconvenience. {{tr "pleaseGoBack"}}

pleaseGoBack=Please go back and check your form entry or try again at a later date.
```

**Comment by kataras** [comment] 2020-09-10 07:41
If the key exist in the locale folder (e.g. `en-US`) then it should be

**Comment by AlbinoGeek** [comment] 2020-09-10 07:45
(in my example above, the key existed in the same file) -- and I am not using INI sections (as I assumed those were not supported), just INI comments. Sections look like:
```ini
[section] ; assuming this is not supported
; however, if it was, you would access this key like: section.key
key=value
```

**Comment by kataras** [comment] 2020-09-10 08:33
> (in my example above, the key existed in the same file) -- and I am not using INI sections (as I assumed those were not supported), just INI comments. Sections look like:
> 
> ```ini
> [section] ; assuming this is not supported
> ; however, if it was, you would access this key like: section.key
> key=value
> ```

They are supported and you should be able to get them like you assumed with `section.key`, internal code for that:

https://github.com/kataras/iris/blob/cf0338d34218403ea3ab79862382b13354ba4221/i18n/loader.go#L330-L348

Let me add an example for that case too, if it doesn't work anymore then it's a bug.

**Comment by AlbinoGeek** [comment] 2020-09-10 11:25
I did not expect that! As I did not see it in the examples, I assumed (incorrectly) that it just wasn't a feature.

Go you! [good job]

**Comment by kataras** [comment] 2020-09-10 11:55
Yeah... examples are missing some details that the framework provides, that's why I am (trying) to write the book :D Thanks for your nice words! Let me know if you have any issues with i18n.

**Comment by kataras** [comment] 2020-09-10 14:54
@AlbinoGeek 

https://github.com/kataras/iris/blob/bfb7b1909648ede627830d072962f45627658a4a/_examples/i18n/i18n-template/locales/en-US/user.ini#L1-L5

https://github.com/kataras/iris/blob/bfb7b1909648ede627830d072962f45627658a4a/_examples/i18n/i18n-template/main.go#L23-L49

https://github.com/kataras/iris/blob/bfb7b1909648ede627830d072962f45627658a4a/_examples/i18n/i18n-template/main.go#L65-L70

**Comment by AlbinoGeek** [comment] 2020-09-13 06:56
@kataras I was not able to reproduce the "nested translation" shown in the example above.

I tried in two ways, and got two different results:

```ini
[user.connections]
Title1 = {{tr nav.User}} Connections
Title2 = {{tr "nav.User"}} Connections
```

```golang
# result1
{{tr nav.User}} Connections
# result2
template: layouts/base.html:30:3: executing "layouts/base.html" at <yield>:
  error calling yield: template: user/connections.html:4:38: executing "user/connections.html" at <call .tr "user.connections.Title2">:
  error calling call: runtime error: index out of range [0] with length 0
```

**Comment by AlbinoGeek** [comment] 2020-09-29 17:00
> @kataras I was not able to reproduce the "nested translation" shown in the example above.
> 
> I tried in two ways, and got two different results:
> 
> ```ini
> [user.connections]
> Title1 = {{tr nav.User}} Connections
> Title2 = {{tr "nav.User"}} Connections
> ```
> 
> ```go
> # result1
> {{tr nav.User}} Connections
> # result2
> template: layouts/base.html:30:3: executing "layouts/base.html" at <yield>:
>   error calling yield: template: user/connections.html:4:38: executing "user/connections.html" at <call .tr "user.connections.Title2">:
>   error calling call: runtime error: index out of range [0] with length 0
> ```
> 
> The first-way `Title1` led to the exact text being displayed, without the sub-translation resolved.
> 
> The second way `Title2` led to a template rendering error being shown in the browser and console.

This appears to be fixed!

**Comment by kataras** [comment] 2020-09-29 17:03
That's great, it's time to close this too then 💯

**Closed** 2020-09-29 17:03 UTC
Labels: status:implemented, type:idea
