### ISSUE TITLE
schema: invalid path "phone"schema: invalid path "phone"

### ISSUE THREAD

**Issue by jiulu313** [kataras/iris#1847] opened 2022-02-26 01:49 UTC
Describe the issue you are facing or ask for help
when my code : 

`
func (c *AccessController) BeforeActivation(b mvc.BeforeActivation) {
	b.Handle("POST","/hello","Hello")
}

func (c *AccessController) Hello() {
	phone := c.Ctx.FormValue("phone")

	fmt.Println(phone)
}
`

request with form ,key is phone,   and report under error 
schema: invalid path "phone"schema: invalid path "phone"

my mvc is v12

**Comment by kataras** [comment] 2022-02-26 19:20
Hello @jiulu313, this is a duplicate of: https://github.com/kataras/iris/issues/1704.

Solution:

```go
func (c * AccessController) HandleError(ctx iris.Context, err error) {
	// to ignore any "schema: invalid path" you can check the error type
	// as we do here and don't stop the execution.
	if iris.IsErrPath(err) {
	     // continue to your "Hello" handler even if some of your form fields are not given by the client.
	    return
	}

	// on any other error, stop the execution of the handler chain.
	ctx.StopExecution()
}
```

**Comment by jiulu313** [comment] 2022-02-27 01:23
@kataras  thank you very much 
I love the kataras , and my site www.helloworld.net use it
thank you

**Comment by kataras** [comment] 2022-02-28 10:40
You are very welcomed @jiulu313! Happy to hear that helloworld.net uses Iris, we can add it on our wikis as well!

**Comment by jiulu313** [comment] 2022-03-02 10:26
@kataras thank you

**Closed** 2022-07-03 11:51 UTC
Labels: 🤔 type:question
