### ISSUE TITLE
[BUG] POST Dependency Injection skipped/fails when `mvc.Controller` contains a `HandleError` method which `returns`s

### ISSUE THREAD

**Issue by AlbinoGeek** [kataras/iris#1629] opened 2020-09-13 19:48 UTC
## Summary

When you fixed `HandleError` supporting `IsErrPath`, my POST pages now send a `500` Internal Server Error with the following error output. Commenting out `HandleError` results in no panic, but the existing `invalid path` error.

## Versions, etc.

|Thing|Version|
|-|-|
|Golang|1.14.7 linux/amd64|
|Iris|master a917ef6|
|Kernel|5.8.4-200.fc32.x86_64|
|OS|Fedora 32 Workstation|

## Code

```golang
func main() {
	// ...
	debugRouter := app.Party("/debug")
	mvc.New(debugRouter).
		Register(user.AuthDependency). // <-- guarantees injection of `c.Connection`
		Handle(&debug.DebugController{
			AuthorizedUserController: user.AuthorizedUserController{
				DB: database,
			},
		})
	// ...
}

// DebugController.go
type DebugController struct {
	user.AuthorizedUserController
}

func (c *DebugController) HandleError(ctx iris.Context, err error) {
	if iris.IsErrPath(err) {
		return // continue.
	}

	ctx.StopWithError(iris.StatusBadRequest, err)
}

func (c *DebugController) PostTest(ctx iris.Context) mvc.Result {
	// vvvv controllers/debug/DebugController.go:87 vvv
	if err := c.AuthorizedUserController.VerifyLogin(ctx); err != nil {
		return err
	}
	
	if ctx.FormValue("action") == "clear" {
		// ...
	}
	
	return nil
}

// Authorized.go
type AuthorizedUserController struct {
	// Connection is injected by AuthDependency, returning the User's Account Connection resource
	Connection *types.Connection
	
	// DB is a Repository used to access Account resources
	DB         *db.DB
}

func (c *AuthorizedUserController) VerifyLogin(ctx iris.Context) mvc.Result {
	// error here, in `c.Connection` being `nil`, yet the Controller was executed
	// `c.Connection` is guaranteed to be set by `AuthDependency` injection, in past versions
	// vvvv controllers/user/Authorized.go:21 vvv
	connection, err := c.DB.FindConnectionByProviderUserID(c.Connection.Provider, c.Connection.UserID)
	// ...
```

## Error Output

```
[WARN] 2020/09/13 12:14 Recovered from a route's Handler('iris/hero.makeHandler.func2')
POST -redacted- HTTP/2.0
Host: -redacted-
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en;q=0.9
Authorization: Basic -redacted-
Cache-Control: max-age=0
Content-Length: 12
Content-Type: application/x-www-form-urlencoded
Cookie: -redacted-
Dnt: 1
Origin: -redacted-
Referer: -redacted-
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36

runtime error: invalid memory address or nil pointer dereference
/usr/lib/golang/src/runtime/panic.go:969
/usr/lib/golang/src/runtime/panic.go:212
/usr/lib/golang/src/runtime/signal_unix.go:695
-redacted-/controllers/user/Authorized.go:21
-redacted-/controllers/debug/DebugController.go:87
/usr/lib/golang/src/reflect/value.go:460
/usr/lib/golang/src/reflect/value.go:321
/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha/hero/handler.go:144
/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha/context/context.go:612
-redacted-/controllers/base/populateViewData.go:22
/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha/context/context.go:612
/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha/middleware/basicauth/basicauth.go:139
/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha/context/context.go:612
/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha/middleware/recover/recover.go:77
/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha/context/context.go:477
/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha/core/router/handler.go:441
/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha/core/router/router.go:110
/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha/context/context.go:612
/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha/middleware/accesslog/accesslog.go:577
/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha/context/context.go:477
/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha/core/router/router.go:158
/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha/middleware/rewrite/rewrite.go:257
/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha/core/router/router_wrapper.go:23
/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha/i18n/i18n.go:543
/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha/core/router/router_wrapper.go:25
/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha/core/router/router_wrapper.go:51
/home/damon/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha/core/router/router.go:322
/usr/lib/golang/src/net/http/server.go:2836
/usr/lib/golang/src/net/http/server.go:3410
/usr/lib/golang/src/net/http/h2_bundle.go:5720
/usr/lib/golang/src/runtime/asm_amd64.s:1373

[WARN] 2020/09/13 12:14 HandleHTTPError executed:
        mvc.Code = 500
        ctx.StatusCode = 500
[WARN] 2020/09/13 12:14
        ctx.GetErr() = runtime error: invalid memory address or nil pointer dereference,
        mvc.Err = runtime error: invalid memory address or nil pointer dereference
```

**Comment by kataras** [comment] 2020-09-13 19:56
@AlbinoGeek I didn't fix the HandleError, I just let the developer to decide to ignore an error and continue, that's all, I've just commented out a single `// return`. 

Now, I don't get it. Why is this a bug? If you register a custom error handler and you are not stopping the execution when you think that the dependency failed to be injected (e..g session is not exist), it's expected  you will get a panic of nil if you are trying to use a dependency that wasn't injected inside your method. Can I have a code snippet so I can explain you better why you getting this error? and let's discuss together what's best to solve cases like that.

**Comment by AlbinoGeek** [comment] 2020-09-13 20:27
The issue is that the user __is logged in__, yet the dependency fails to inject, only if a `HandleError` is defined, is the behaviour I am seeing (as illogical as it sounds.) Which leads me to believe that dependency injection doesn't run when an error is returned if the `mvc.Controller` has an `HandleError` defined which returns without stopping execution, which sounds a little confusing.

Using the following code results in the same `500` error:

```golang
func (c *DebugController) HandleError(ctx iris.Context, err error) {
	golog.Warnf("DebugController.HandleError: %v", err)
	if iris.IsErrPath(err) {
		return // continue.
	}

	if err != hero.ErrStopExecution {
		if status := ctx.GetStatusCode(); status == 0 || !context.StatusCodeNotSuccessful(status) {
			ctx.StatusCode(hero.DefaultErrStatusCode)
		}

		_, _ = ctx.WriteString(err.Error())
	}

	ctx.StopExecution()
	// ctx.StopWithError(iris.StatusBadRequest, err)
}
```

Results in

```
[WARN] 2020/09/13 13:24 DebugController.HandleError: schema: invalid path "action"                    
[WARN] 2020/09/13 13:24 Recovered from a route's Handler('iris/hero.makeHandler.func2')
POST /debug/accesslog HTTP/2.0
// ...
```

---

Whatever code fires this error upstream, makes dependency injection get skipped for the Handler, so that even if I `return` from the error, there's no way to continue the Handler, because the injected dependency it relies on is unavailable.

**Comment by AlbinoGeek** [comment] 2020-09-13 20:29
This can be confirmed by adding another log line:

```golang
func (c *DebugController) HandleError(ctx iris.Context, err error) {
	golog.Warnf("DebugController.HandleError: %v", err)
	golog.Warnf("Dependency: %v", c.Connection) // <-- Dependency Injection has not occurred yet!
	if iris.IsErrPath(err) {
		return // continue.
	}
```

```
[WARN] 2020/09/13 13:28 Dependency: <nil> 
```

**Comment by kataras** [comment] 2020-09-13 21:55
@AlbinoGeek The problem is that HandleError can ignore errors on Handlers not on struct fields, you have a struct field dependency, let me fix that too.

**Comment by kataras** [comment] 2020-09-13 21:57
@AlbinoGeek The problem is that HandleError can ignore errors on Handlers not on struct fields, you have a struct field dependency which does not uses the `HandleError` at all with the logic of: "if a controller's field is not injected correctly, then dont run any method, they maybe call the field and get a nil panic", let me fix that too.

**Comment by kataras** [comment] 2020-09-13 22:10
OK @AlbinoGeek it should be fixed now, can you confirm? (update to `@master`)

**Closed** 2020-09-13 22:10 UTC
Labels: type:bug

**Comment by AlbinoGeek** [comment] 2020-09-13 22:29
After updating to the latest commit, the following code now works (???)
```golang
func (c *DebugController) PostTest(ctx iris.Context) mvc.Result {
	if _, _, err := user.VerifyLogin(c.DB, ctx, c.Connection); err != nil {
		return err
	}

	if ctx.FormValue("action") == "clear" {
		// ...
	}
}
```

I have no idea why this works now, but it does, and I'm quite happy!

**Comment by kataras** [comment] 2020-09-13 23:12
Sure it does 👍 Thanks for that bug report once again (check [my response here](https://github.com/kataras/iris/issues/1627#issuecomment-691738795) too)
