### ISSUE TITLE
Dynamic routing cannot match url like /msg/xxx%2Fxxx

### ISSUE THREAD

**Issue by ThomasZenX** [kataras/iris#1271] opened 2019-06-06 10:43 UTC
the route can't be matched by the url /msg/xxx%2Fxxx

```
app.Get("/msg/{text}", func(ctx iris.Context) {
      ... ...
})
```

**Comment by kataras** [comment] 2019-06-06 19:52
Hello @ThomasZenX, by-default iris will match the path based on the `request.URL.Path` but there is the `WithPathEscape` option which changes that behavior and the path is retrieved by `request.URL.EscapedPath()` :

```go
app.Run(iris.Addr(":8080"), iris.WithPathEscape)
```

The problem is that it still does not work in your case because it wraps the path result and  `decode`  for any url parameters and that converts the `%2` to  `/`. This is fixed on the upcoming version 11.2, I'll push a direct commit to the `master` and `v11` branch so you can grab that fix today.

**Closed** 2019-06-06 20:06 UTC
