### ISSUE TITLE
how to use `RenderXML` with `ctx.Problem`?

### ISSUE THREAD

**Issue by lmq1117** [kataras/iris#1389] opened 2019-10-31 03:42 UTC
when i run _examples\routing\http-errors\main.go
use json it works ok,but when use xml ,it doesn't work. it's the code
```
	// Response like JSON but with indent of "  " and
	// content type of "application/problem+json"
	ctx.Problem(newProductProblem("product name", "problem error details"), iris.ProblemOptions{
		RenderXML: true,
		XML:       iris.XML{Indent: "  "},
		RetryAfter: 300,
	})
```

**Comment by kataras** [comment] 2019-10-31 03:51
Hello @lmq1117, you have right, the example does not work, give me some time to debug and find the cause of the problem.

**Comment by kataras** [comment] 2019-10-31 04:33
Hello @lmq1117, the problem is that the browser does not handle the 400 (bad request) + `application/problem+xml` content type, **the server sends the response correctly**. If you open the developer tools you will see the status code of 400 and the XML preview, or test with postman:

![act](https://user-images.githubusercontent.com/22900943/67918938-157af280-fba7-11e9-88f5-b4d6334f601b.png)

You can also see that if you `ctx.StatusCode(iris.StatusOK)` right after the `ctx.Problem(...)`, then the browser will show the XML contents in the page.

It's not a bug, it's an expected behavior from browser vendors. Closing this issue, if you need further assistance please open a new issue.

**Closed** 2019-10-31 04:33 UTC

**Comment by lmq1117** [comment] 2019-10-31 04:43
yes,with postman it works ok,3ks

**Comment by kataras** [comment] 2019-10-31 06:23
You are welcome @lmq1117!
